---
services:
  remotescan:
    image: brikim/remotescan:latest
    container_name: remotescan
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Chicago
    volumes:
      - /docker/remotescan/config:/config
      - /docker/remotescan/logs:/logs
      - /pathToMedia:/media
    restart: unless-stopped